export interface ResolutionItem {
    value: number;
    unit: 'g' | 'unidade' | 'ml';
}

// Dados extraídos do "APÊNDICE 1" da resolução (páginas 25-29)
// Chave: NOME DO PRODUTO EM MAIÚSCULO
// Valor: { value: [valor da coluna 'Per capita mensal c/ fator de correção'], unit: 'g' | 'unidade' | 'ml' }
export const resolutionData: Record<string, ResolutionItem> = {
    'ABACATE': { value: 1096, unit: 'g' },
    'ABACAXI': { value: 1096, unit: 'g' },
    'ABÓBORA': { value: 735, unit: 'g' },
    'ABOBORA MADURA': { value: 735, unit: 'g' },
    'ABOBRINHA BRASILEIRA': { value: 583, unit: 'g' },
    'ABOBRINHA ITALIANA': { value: 583, unit: 'g' },
    'ABOBRINHA': { value: 583, unit: 'g' },
    'ACELGA': { value: 635, unit: 'g' },
    'AÇÚCAR REFINADO': { value: 940 + 1236, unit: 'g' },
    'AÇÚCAR': { value: 940 + 1236, unit: 'g' },
    'AGRIÃO': { value: 1161, unit: 'g' },
    'ALFACE CRESPA': { value: 783, unit: 'g' },
    'ALFACE LISA': { value: 783, unit: 'g' },
    'ALFACE': { value: 783, unit: 'g' },
    'ALHO': { value: 389, unit: 'g' },
    'ALMEIRÃO': { value: 574, unit: 'g' },
    'ARROZ': { value: 6327, unit: 'g' },
    'ARROZ AGULHINHA': { value: 6327, unit: 'g' },
    'BANANA NANICA': { value: 26, unit: 'unidade' },
    'BATATA': { value: 2388, unit: 'g' },
    'BATATA COMUM': { value: 2388, unit: 'g' },
    'BATATA DOCE': { value: 696, unit: 'g' },
    'BATATA DOCE AMARELA': { value: 696, unit: 'g' },
    'BERINJELA': { value: 496, unit: 'g' },
    'BETERRABA': { value: 587, unit: 'g' },
    'BRÓCOLIS': { value: 996, unit: 'g' },
    'CAFÉ': { value: 940, unit: 'g' },
    'CAFÉ TORRADO E MOÍDO': { value: 940, unit: 'g' },
    'CARNE BOVINA': { value: 4872, unit: 'g' },
    'CARNE SECA': { value: 535, unit: 'g' },
    'CEBOLA': { value: 1582, unit: 'g' },
    'CENOURA': { value: 761, unit: 'g' },
    'CHUCHU': { value: 718, unit: 'g' },
    'COUVE-FLOR': { value: 674, unit: 'g' },
    'COUVE FLOR': { value: 674, unit: 'g' },
    'COUVE MANTEIGA': { value: 665, unit: 'g' },
    'ESCAROLA': { value: 940, unit: 'g' },
    'ESPINAFRE': { value: 900, unit: 'g' },
    'EXTRATO DE TOMATE': { value: 232, unit: 'g' },
    'FARINHA DE MANDIOCA': { value: 124, unit: 'g' },
    'FARINHA DE MILHO': { value: 124, unit: 'g' },
    'FARINHA DE TRIGO': { value: 312, unit: 'g' },
    'FEIJÃO PRETO': { value: 104, unit: 'g' },
    'FEIJÃO': { value: 3164, unit: 'g' },
    'FÍGADO DE BOVINO': { value: 214, unit: 'g' },
    'FÍGADO': { value: 214, unit: 'g' },
    'FRANGO': { value: 2245, unit: 'g' },
    'FUBÁ': { value: 124, unit: 'g' },
    'FUBÁ DE MILHO': { value: 124, unit: 'g' },
    'LARANJA': { value: 26, unit: 'unidade' },
    'LARANJA PÊRA': { value: 26, unit: 'unidade' },
    'LEITE': { value: 15332, unit: 'ml' },
    'LEITE DE VACA': { value: 15332, unit: 'ml' },
    'LIMÃO': { value: 8, unit: 'unidade' },
    'LIMÃO TAITI': { value: 8, unit: 'unidade' },
    'LINGUIÇA': { value: 783, unit: 'g' },
    'MANDIOCA': { value: 687, unit: 'g' },
    'MANGA': { value: 5, unit: 'unidade' },
    'MARGARINA': { value: 627, unit: 'g' },
    'MARGARINA VEGETAL': { value: 627, unit: 'g' },
    'MACARRÃO': { value: 361, unit: 'g' },
    'MASSA ALIMENTÍCIA': { value: 361, unit: 'g' },
    'MELANCIA': { value: 1414, unit: 'g' },
    'ÓLEO DE SOJA': { value: 1886, unit: 'ml' },
    'ÓLEO': { value: 1886, unit: 'ml' },
    'OVO': { value: 9, unit: 'unidade' },
    'OVOS': { value: 9, unit: 'unidade' },
    'PÃO FRANCÊS': { value: 4654, unit: 'g' },
    'PÃO': { value: 4654, unit: 'g' },
    'PEIXE': { value: 613, unit: 'g' },
    'PEPINO': { value: 1079, unit: 'g' },
    'PIMENTÃO': { value: 657, unit: 'g' },
    'QUIABO': { value: 531, unit: 'g' },
    'REPOLHO': { value: 587, unit: 'g' },
    'SAL': { value: 505, unit: 'g' },
    'SAL REFINADO': { value: 505, unit: 'g' },
    'SALSICHA': { value: 452, unit: 'g' },
    'SUCO DE FRUTAS': { value: 1278, unit: 'ml' },
    'TOMATE': { value: 1383, unit: 'g' },
    'VAGEM': { value: 478, unit: 'g' },
    'VINAGRE': { value: 627, unit: 'ml' },
};
